import {isDefined, panic} from "@opendaw/lib-std"
import {ScriptDspBlock, ScriptDspExample} from "./ScriptDspBlock"
import {ScriptDspUtilityBlocks} from "./ScriptDspUtilities"
import {ScriptDspOscillatorBlocks} from "./ScriptDspOscillators"
import {ScriptDspWavetableBlocks} from "./ScriptDspWavetables"
import {ScriptDspFilterBlocks} from "./ScriptDspFilters"
import {ScriptDspShaperBlocks} from "./ScriptDspShapers"
import {ScriptDspExamples} from "./ScriptDspExamples"

export namespace ScriptDsp {
    export const version = 1
    export const blocks: ReadonlyArray<ScriptDspBlock> = [
        ...ScriptDspUtilityBlocks, ...ScriptDspOscillatorBlocks, ...ScriptDspWavetableBlocks,
        ...ScriptDspFilterBlocks, ...ScriptDspShaperBlocks
    ]
    export const blockNames: ReadonlyArray<string> = blocks.map(block => block.name)
    export const examples: ReadonlyArray<ScriptDspExample> = ScriptDspExamples

    const BeginMarker = "// openDAW DSP library"
    const EndMarker = "// end of openDAW DSP library"
    const LibraryRegion = /^\/\/ openDAW DSP library[^\n]*\n[\s\S]*?^\/\/ end of openDAW DSP library[^\n]*(?:\n|$)/m
    const CollapsedLine = /^\/\/ openDAW DSP library[^\n]*\(collapsed[^\n]*(?:\n|$)/gm
    const Comments = /\/\*[\s\S]*?\*\/|\/\/[^\n]*/g
    const Usage = /\bDsp\.([A-Za-z_$][\w$]*)/g
    const HelperNames: ReadonlyArray<string> = ["link", "include", "strip", "isLinked", "blocks", "version"]
    const byName = new Map(blocks.map(block => [block.name, block]))
    const byExport = new Map(blocks.flatMap(block => block.exports.map(name => [name, block] as const)))

    export const resolve = (names: ReadonlyArray<string>): ReadonlyArray<ScriptDspBlock> => {
        const ordered: Array<ScriptDspBlock> = []
        const visit = (name: string): void => {
            const block = byName.get(name)
            if (!isDefined(block)) {return panic(`Unknown DSP block '${name}'. Available: ${blockNames.join(", ")}`)}
            if (ordered.includes(block)) {return}
            block.requires.forEach(visit)
            ordered.push(block)
        }
        visit("core")
        names.forEach(visit)
        return ordered
    }

    export const include = (names: ReadonlyArray<string>): string => {
        const resolved = resolve(names)
        const header = `${BeginMarker} v${version}: ${resolved.map(block => block.name).join(", ")}. ` +
            "Generated by Dsp.link, your code follows the end marker."
        return [header, "const Dsp = (() => {", "\"use strict\"", "const Dsp = {}",
            ...resolved.map(block => `{${block.source}}`), "return Object.freeze(Dsp)", "})()", EndMarker, ""].join("\n")
    }

    export const isLinked = (code: string): boolean => LibraryRegion.test(code)

    export const strip = (code: string): string => code.replace(LibraryRegion, "").replace(CollapsedLine, "")

    export const collapse = (code: string): string => code.replace(LibraryRegion, match => {
        const header = match.slice(0, match.indexOf("\n"))
        return `${header.replace(/\. Generated by Dsp\.link.*$/, "")} (collapsed here, linked automatically when assigned to device.code)\n`
    })

    export const usedBlocks = (code: string): ReadonlyArray<string> => {
        const names = new Set<string>()
        for (const [, member] of strip(code).replace(Comments, "").matchAll(Usage)) {
            if (HelperNames.includes(member)) {continue}
            const block = byExport.get(member)
            if (!isDefined(block)) {
                return panic(`Unknown Dsp.${member}. Available: ${Array.from(byExport.keys()).join(", ")}`)
            }
            names.add(block.name)
        }
        return Array.from(names)
    }

    export const link = (code: string): string => {
        const user = strip(code)
        return include(usedBlocks(user)) + user
    }

    export const linkIfUsed = (code: string): string => usedBlocks(strip(code)).length > 0 ? link(code) : code

    export const reference = (device: string): string => {
        const listed = examples.filter(example => example.device === device)
        const exampleLine = listed.length === 0 ? [] : [`Examples built only from the library (device_reference example): ${
            listed.map(example => `${example.name} (${example.summary})`).join("; ")}.`]
        return [
            "## DSP library (Dsp.*, use it instead of hand-written DSP)",
            "Proven, allocation-free building blocks for Apparat and Werkstatt code: band-limited and wavetable oscillators, " +
            "ZDF filters, formant and comb filters, oversampled waveshapers, envelopes, LFOs and a voice manager. " +
            "Assigning code that uses `Dsp.Name` to `device.code` in run_script links the library automatically: exactly the " +
            "referenced blocks (dependencies resolved) are prepended, so the device code stays self-contained. Examples " +
            "show the library as one collapsed comment line; assign them as they are. `Dsp.link(code)` does the same " +
            "explicitly, `Dsp.strip(device.code)` returns your part for edits. `Dsp.include(\"svf\", ...)` adds blocks by name.",
            "Rules: create every block in the Processor or voice constructor (Dsp.Voices preallocates voices), never in " +
            "noteOn or process(); call next()/process() once per sample. Every block reads the `sampleRate` global, clamps " +
            "its setters to the documented ranges, and is NaN- and denormal-safe. Costs are per call on a desktop CPU; the " +
            "device budget is about 20000 ns per sample frame at 48 kHz for everything, keep a patch below a quarter of it.",
            ...blocks.map(block => block.doc),
            ...exampleLine
        ].join("\n")
    }
}
