import {describe, expect, it} from "vitest"
import {createFixture} from "./Fixture"
import {Instruments} from "../Api"

describe("Audio units", () => {
    it("creates instrument units with a default track and unique names", () => {
        const {project} = createFixture()
        const vapo = project.addInstrumentUnit("Vaporisateur")
        expect(vapo.kind).toBe("instrument")
        expect(vapo.instrument.key).toBe("Vaporisateur")
        expect(vapo.label).toBe("Vaporisateur")
        expect(vapo.noteTracks.length).toBe(1)
        expect(vapo.audioTracks.length).toBe(0)
        expect(vapo.tracks[0].audioUnit).toBe(vapo)
        expect(vapo.output).toBe(project.output)
        const second = project.addInstrumentUnit("Vaporisateur")
        expect(second.label).toBe("Vaporisateur 2")
        const tape = project.addInstrumentUnit("Tape", {label: "Drums", volume: -6, panning: 0.25, mute: true})
        expect(tape.label).toBe("Drums")
        expect(tape.audioTracks.length).toBe(1)
        expect(tape.noteTracks.length).toBe(0)
        expect(tape.volume).toBe(-6)
        expect(tape.panning).toBe(0.25)
        expect(tape.mute).toBe(true)
        expect(project.instrumentUnits.map(unit => unit.label)).toEqual(["Vaporisateur", "Vaporisateur 2", "Drums"])
        expect(project.audioUnits.map(unit => unit.index)).toEqual([0, 1, 2, 3])
        expect(project.output.index).toBe(3)
        expect(project.findAudioUnit("Drums")).toBe(tape)
        expect(project.findAudioUnit("Nope")).toBeNull()
    })

    it("creates every instrument type", () => {
        const {project} = createFixture()
        const keys: ReadonlyArray<keyof Instruments> = ["Vaporisateur", "Playfield", "Nano", "Soundfont", "MIDIOutput", "Tape", "Neon", "Tubular", "Cubed", "Apparat"]
        keys.forEach(key => {
            const unit = project.addInstrumentUnit(key)
            expect(unit.instrument.key).toBe(key)
            expect(unit.instrument.audioUnit).toBe(unit)
            expect(unit.instrument.enabled).toBe(true)
        })
        expect(() => project.addInstrumentUnit("Bogus" as keyof Instruments)).toThrow(RangeError)
    })

    it("applies initial instrument parameters", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur", {label: "Lead"}, {cutoff: 500, lfo: {rate: 2}, oscillators: [{waveform: 3}, {volume: -12}]})
        expect(unit.instrument.cutoff).toBe(500)
        expect(unit.instrument.lfo.rate).toBe(2)
        expect(unit.instrument.oscillators[0].waveform).toBe(3)
        expect(unit.instrument.oscillators[1].volume).toBe(-12)
        expect(() => project.addInstrumentUnit("Vaporisateur", {}, {bogus: 1} as any)).toThrow(TypeError)
    })

    it("creates bus units and routes outputs", () => {
        const {project} = createFixture()
        const synth = project.addInstrumentUnit("Vaporisateur")
        const group = project.addGroupUnit({label: "Synths", color: "red"})
        const aux = project.addAuxUnit({label: "Reverb", icon: "Flask"})
        expect(group.kind).toBe("group")
        expect(aux.kind).toBe("auxiliary")
        expect(group.label).toBe("Synths")
        expect(group.color).toBe("red")
        expect(aux.icon).toBe("Flask")
        expect(() => aux.icon = "NotAnIcon").toThrow(RangeError)
        expect(project.audioUnits.map(unit => unit.kind)).toEqual(["instrument", "auxiliary", "group", "output"])
        synth.output = group
        expect(synth.output).toBe(group)
        group.output = null
        expect(group.output).toBeNull()
        group.output = project.output
        expect(group.output).toBe(project.output)
        expect(() => synth.output = synth as any).toThrow(TypeError)
        expect(() => group.output = group).toThrow(RangeError)
    })

    it("reads output as null on the output unit (it targets the hardware, not a bus)", () => {
        const {project} = createFixture()
        const synth = project.addInstrumentUnit("Vaporisateur", {label: "Lead"})
        const group = project.addGroupUnit({label: "Synths"})
        synth.output = group
        expect(project.output.output).toBeNull()
        expect(project.audioUnits.map(unit => [unit.label, unit.output?.label ?? null]))
            .toEqual([["Lead", "Synths"], ["Synths", project.output.label], [project.output.label, null]])
        expect(() => project.output.output = group).toThrow(/output unit feeds the audio hardware/)
        expect(() => project.output.output = null).toThrow(TypeError)
    })

    it("manages sends", () => {
        const {project} = createFixture()
        const synth = project.addInstrumentUnit("Vaporisateur")
        const aux = project.addAuxUnit({label: "Delay"})
        const group = project.addGroupUnit()
        const send = synth.addSend(aux, {amount: -12, pan: -0.5, mode: "pre"})
        expect(send.amount).toBe(-12)
        expect(send.pan).toBe(-0.5)
        expect(send.mode).toBe("pre")
        expect(send.target).toBe(aux)
        expect(send.audioUnit).toBe(synth)
        expect(send.index).toBe(0)
        const second = synth.addSend(group)
        expect(second.amount).toBe(-6)
        expect(second.mode).toBe("post")
        expect(second.index).toBe(1)
        expect(synth.sends.length).toBe(2)
        expect(() => synth.addSend(synth as any)).toThrow(TypeError)
        expect(() => aux.addSend(aux)).toThrow(RangeError)
        expect(() => send.mode = "sideways" as any).toThrow(RangeError)
        send.remove()
        expect(synth.sends.length).toBe(1)
        expect(second.index).toBe(0)
        aux.addSend(group, {amount: 0})
        expect(aux.sends.length).toBe(1)
    })

    it("removes units and reindexes the rest", () => {
        const {project} = createFixture()
        const first = project.addInstrumentUnit("Vaporisateur")
        const second = project.addInstrumentUnit("Nano")
        const aux = project.addAuxUnit()
        second.addSend(aux)
        first.remove()
        expect(project.audioUnits.map(unit => unit.index)).toEqual([0, 1, 2])
        expect(project.instrumentUnits.length).toBe(1)
        expect(() => first.volume).toThrow()
        aux.remove()
        expect(second.sends.length).toBe(0)
        expect(project.audioUnits.length).toBe(2)
        expect(() => project.output.remove()).toThrow()
    })

    it("replaces instruments", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur", {label: "Keys"})
        const nano = unit.setInstrument("Nano", {volume: -9})
        expect(unit.instrument).toBe(nano)
        expect(nano.key).toBe("Nano")
        expect(nano.volume).toBe(-9)
        expect(unit.label).toBe("Keys")
        expect(unit.noteTracks.length).toBe(1)
        unit.setInstrument("Tape")
        expect(unit.instrument.key).toBe("Tape")
    })

    it("clamps and validates channel strip values", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur")
        unit.volume = 20
        expect(unit.volume).toBe(6)
        unit.volume = -200
        expect(unit.volume).toBe(-96)
        unit.panning = 2
        expect(unit.panning).toBe(1)
        expect(() => unit.mute = 1 as any).toThrow(TypeError)
        expect(() => unit.volume = "loud" as any).toThrow(TypeError)
        unit.label = "Bass"
        expect(unit.label).toBe("Bass")
        expect(unit.instrument.label).toBe("Bass")
    })

    it("manages tracks", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur")
        const first = unit.noteTracks[0]
        const second = unit.addNoteTrack({enabled: false})
        expect(second.enabled).toBe(false)
        expect(second.index).toBe(1)
        const inserted = unit.addNoteTrack({}, 0)
        expect(inserted.index).toBe(0)
        expect(first.index).toBe(1)
        expect(second.index).toBe(2)
        expect(unit.tracks.map(track => track.type)).toEqual(["notes", "notes", "notes"])
        const audio = unit.addAudioTrack()
        expect(audio.type).toBe("audio")
        const value = unit.addValueTrack(unit, "volume")
        expect(value.type).toBe("value")
        expect(value.target).toBe(unit)
        expect(value.parameter).toBe("volume")
        expect(unit.valueTrack(unit, "volume")).toBe(value)
        expect(unit.valueTrack(unit, "panning")).toBeNull()
        expect(() => unit.addValueTrack(unit, "volume")).toThrow(RangeError)
        expect(() => unit.addValueTrack(unit, "bogus" as any)).toThrow(RangeError)
        inserted.remove()
        expect(first.index).toBe(0)
        expect(unit.tracks.length).toBe(4)
        expect(first.owner).toBe(unit)
        expect(first.audioUnit).toBe(unit)
        expect(first.excludePianoMode).toBe(false)
        first.excludePianoMode = true
        expect(first.excludePianoMode).toBe(true)
        expect(() => first.excludePianoMode = "yes" as any).toThrow(TypeError)
    })

    it("automates nested device parameters", () => {
        const {project} = createFixture()
        const unit = project.addInstrumentUnit("Vaporisateur")
        const track = unit.addValueTrack(unit.instrument, "lfo.rate")
        expect(track.target).toBe(unit.instrument)
        expect(track.parameter).toBe("lfo.rate")
        const osc = unit.addValueTrack(unit.instrument, "oscillators.1.volume")
        expect(osc.parameter).toBe("oscillators.1.volume")
        const delay = unit.addAudioEffect("Delay")
        const feedback = unit.addValueTrack(delay, "feedback")
        expect(feedback.target).toBe(delay)
        expect(() => unit.addValueTrack(delay, "label" as any)).toThrow(RangeError)
    })
})
